# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import kv_pb2 as kv__pb2


class ReplicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Replicate = channel.unary_unary(
                '/kv.Replicator/Replicate',
                request_serializer=kv__pb2.ReplicateRequest.SerializeToString,
                response_deserializer=kv__pb2.ReplicateResponse.FromString,
                )
        self.StreamBucket = channel.unary_stream(
                '/kv.Replicator/StreamBucket',
                request_serializer=kv__pb2.StreamBucketRequest.SerializeToString,
                response_deserializer=kv__pb2.StreamKV.FromString,
                )


class ReplicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Replicate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamBucket(self, request, context):
        """Server-side streaming for bucket transfer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Replicate': grpc.unary_unary_rpc_method_handler(
                    servicer.Replicate,
                    request_deserializer=kv__pb2.ReplicateRequest.FromString,
                    response_serializer=kv__pb2.ReplicateResponse.SerializeToString,
            ),
            'StreamBucket': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamBucket,
                    request_deserializer=kv__pb2.StreamBucketRequest.FromString,
                    response_serializer=kv__pb2.StreamKV.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kv.Replicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Replicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Replicate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kv.Replicator/Replicate',
            kv__pb2.ReplicateRequest.SerializeToString,
            kv__pb2.ReplicateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamBucket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/kv.Replicator/StreamBucket',
            kv__pb2.StreamBucketRequest.SerializeToString,
            kv__pb2.StreamKV.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
