# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08kv.proto\x12\x02kv\"7\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\x05\"?\n\x10ReplicateRequest\x12\x18\n\x02kv\x18\x01 \x01(\x0b\x32\x0c.kv.KeyValue\x12\x11\n\tfrom_node\x18\x02 \x01(\t\"0\n\x11ReplicateResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"F\n\x13StreamBucketRequest\x12\x11\n\tbucket_id\x18\x01 \x01(\x05\x12\r\n\x05start\x18\x02 \x01(\x05\x12\r\n\x05limit\x18\x03 \x01(\x05\"$\n\x08StreamKV\x12\x18\n\x02kv\x18\x01 \x01(\x0b\x32\x0c.kv.KeyValue2\x7f\n\nReplicator\x12\x38\n\tReplicate\x12\x14.kv.ReplicateRequest\x1a\x15.kv.ReplicateResponse\x12\x37\n\x0cStreamBucket\x12\x17.kv.StreamBucketRequest\x1a\x0c.kv.StreamKV0\x01\x62\x06proto3')



_KEYVALUE = DESCRIPTOR.message_types_by_name['KeyValue']
_REPLICATEREQUEST = DESCRIPTOR.message_types_by_name['ReplicateRequest']
_REPLICATERESPONSE = DESCRIPTOR.message_types_by_name['ReplicateResponse']
_STREAMBUCKETREQUEST = DESCRIPTOR.message_types_by_name['StreamBucketRequest']
_STREAMKV = DESCRIPTOR.message_types_by_name['StreamKV']
KeyValue = _reflection.GeneratedProtocolMessageType('KeyValue', (_message.Message,), {
  'DESCRIPTOR' : _KEYVALUE,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.KeyValue)
  })
_sym_db.RegisterMessage(KeyValue)

ReplicateRequest = _reflection.GeneratedProtocolMessageType('ReplicateRequest', (_message.Message,), {
  'DESCRIPTOR' : _REPLICATEREQUEST,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.ReplicateRequest)
  })
_sym_db.RegisterMessage(ReplicateRequest)

ReplicateResponse = _reflection.GeneratedProtocolMessageType('ReplicateResponse', (_message.Message,), {
  'DESCRIPTOR' : _REPLICATERESPONSE,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.ReplicateResponse)
  })
_sym_db.RegisterMessage(ReplicateResponse)

StreamBucketRequest = _reflection.GeneratedProtocolMessageType('StreamBucketRequest', (_message.Message,), {
  'DESCRIPTOR' : _STREAMBUCKETREQUEST,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.StreamBucketRequest)
  })
_sym_db.RegisterMessage(StreamBucketRequest)

StreamKV = _reflection.GeneratedProtocolMessageType('StreamKV', (_message.Message,), {
  'DESCRIPTOR' : _STREAMKV,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.StreamKV)
  })
_sym_db.RegisterMessage(StreamKV)

_REPLICATOR = DESCRIPTOR.services_by_name['Replicator']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KEYVALUE._serialized_start=16
  _KEYVALUE._serialized_end=71
  _REPLICATEREQUEST._serialized_start=73
  _REPLICATEREQUEST._serialized_end=136
  _REPLICATERESPONSE._serialized_start=138
  _REPLICATERESPONSE._serialized_end=186
  _STREAMBUCKETREQUEST._serialized_start=188
  _STREAMBUCKETREQUEST._serialized_end=258
  _STREAMKV._serialized_start=260
  _STREAMKV._serialized_end=296
  _REPLICATOR._serialized_start=298
  _REPLICATOR._serialized_end=425
# @@protoc_insertion_point(module_scope)
