# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kv.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kv.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08kv.proto\x12\x02kv\"7\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\x04\"?\n\x10ReplicateRequest\x12\x18\n\x02kv\x18\x01 \x01(\x0b\x32\x0c.kv.KeyValue\x12\x11\n\tfrom_node\x18\x02 \x01(\t\"0\n\x11ReplicateResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x11MerkleRootRequest\x12\x11\n\tpartition\x18\x01 \x01(\t\"\"\n\x12MerkleRootResponse\x12\x0c\n\x04root\x18\x01 \x01(\t\"K\n\x0cRangeRequest\x12\x11\n\tpartition\x18\x01 \x01(\t\x12\x14\n\x0cstart_bucket\x18\x02 \x01(\r\x12\x12\n\nend_bucket\x18\x03 \x01(\r\"*\n\rRangeResponse\x12\x19\n\x03kvs\x18\x01 \x03(\x0b\x32\x0c.kv.KeyValue2\xbc\x01\n\nReplicator\x12\x38\n\tReplicate\x12\x14.kv.ReplicateRequest\x1a\x15.kv.ReplicateResponse\x12>\n\rGetMerkleRoot\x12\x15.kv.MerkleRootRequest\x1a\x16.kv.MerkleRootResponse\x12\x34\n\rTransferRange\x12\x10.kv.RangeRequest\x1a\x11.kv.RangeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEYVALUE']._serialized_start=16
  _globals['_KEYVALUE']._serialized_end=71
  _globals['_REPLICATEREQUEST']._serialized_start=73
  _globals['_REPLICATEREQUEST']._serialized_end=136
  _globals['_REPLICATERESPONSE']._serialized_start=138
  _globals['_REPLICATERESPONSE']._serialized_end=186
  _globals['_MERKLEROOTREQUEST']._serialized_start=188
  _globals['_MERKLEROOTREQUEST']._serialized_end=226
  _globals['_MERKLEROOTRESPONSE']._serialized_start=228
  _globals['_MERKLEROOTRESPONSE']._serialized_end=262
  _globals['_RANGEREQUEST']._serialized_start=264
  _globals['_RANGEREQUEST']._serialized_end=339
  _globals['_RANGERESPONSE']._serialized_start=341
  _globals['_RANGERESPONSE']._serialized_end=383
  _globals['_REPLICATOR']._serialized_start=386
  _globals['_REPLICATOR']._serialized_end=574
# @@protoc_insertion_point(module_scope)
