# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import kv_pb2 as kv__pb2


class ReplicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Replicate = channel.unary_unary(
                '/kv.Replicator/Replicate',
                request_serializer=kv__pb2.ReplicateRequest.SerializeToString,
                response_deserializer=kv__pb2.ReplicateResponse.FromString,
                )
        self.GetMerkleRoot = channel.unary_unary(
                '/kv.Replicator/GetMerkleRoot',
                request_serializer=kv__pb2.MerkleRootRequest.SerializeToString,
                response_deserializer=kv__pb2.MerkleRootResponse.FromString,
                )
        self.TransferRange = channel.unary_unary(
                '/kv.Replicator/TransferRange',
                request_serializer=kv__pb2.RangeRequest.SerializeToString,
                response_deserializer=kv__pb2.RangeResponse.FromString,
                )


class ReplicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Replicate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMerkleRoot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Replicate': grpc.unary_unary_rpc_method_handler(
                    servicer.Replicate,
                    request_deserializer=kv__pb2.ReplicateRequest.FromString,
                    response_serializer=kv__pb2.ReplicateResponse.SerializeToString,
            ),
            'GetMerkleRoot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMerkleRoot,
                    request_deserializer=kv__pb2.MerkleRootRequest.FromString,
                    response_serializer=kv__pb2.MerkleRootResponse.SerializeToString,
            ),
            'TransferRange': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferRange,
                    request_deserializer=kv__pb2.RangeRequest.FromString,
                    response_serializer=kv__pb2.RangeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kv.Replicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Replicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Replicate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kv.Replicator/Replicate',
            kv__pb2.ReplicateRequest.SerializeToString,
            kv__pb2.ReplicateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMerkleRoot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kv.Replicator/GetMerkleRoot',
            kv__pb2.MerkleRootRequest.SerializeToString,
            kv__pb2.MerkleRootResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TransferRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kv.Replicator/TransferRange',
            kv__pb2.RangeRequest.SerializeToString,
            kv__pb2.RangeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
